gateway:
  deployable-mcp-servers:
    commit-diff-context-mcp:
      name: commit-diff-context-mcp
      command: bash
      arguments: gradlew commit-diff-context-mcp:build -x test
      directory: /Users/hayde/IdeaProjects/commit-diff-context-parent
      copy-to-artifact-path: /Users/hayde/IdeaProjects/commit-diff-context-parent/mcp-tool-gateway/ctx_bin
      copy-from-artifact-path: /Users/hayde/IdeaProjects/commit-diff-context-parent/commit-diff-context-mcp/build/libs/commit-diff-context-mcp.jar
  fail-on-mcp-client-init: false
  mcp-servers-json-location: file:/Users/hayde/IdeaProjects/commit-diff-context-parent/mcp-tool-gateway/build/resources/main/mcp-servers/servers-prod.json

server.port: 8081


otel:
  instrumentation:
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    jdbc:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
management:
  otlp:
    metrics:
      export:
        enabled: false

graphql-props:
  port: 8084
  url: http://localhost:8084/graphql

spring:
  ai:
    vectorstore.type: none
    mcp:
      server:
        stdio: true
        enabled: true
  docker:
    compose:
      file: file:/Users/hayde/IdeaProjects/commit-diff-context-parent/mcp-tool-gateway/src/main/resources/docker/docker-compose.yml
      enabled: false