gateway:
  deployable-mcp-servers:
    test-mcp-server:
      name: test-mcp-server
      deploy-command: ./gradlew :test-mcp-server bootJar
      directory: /Users/hayde/IdeaProjects/commit-diff-context-parent
#    commit-diff-context-mcp:
#      name: commit-diff-context-mcp
#      deploy-command: ./gradlew :commit-diff-context-mcp bootJar
#      directory: /Users/hayde/IdeaProjects/commit-diff-context-parent
  fail-on-mcp-client-init: false
  mcp-servers-json-location: classpath:mcp-servers/servers.json

server.port: 8081

otel:
  instrumentation:
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    jdbc:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
management:
  otlp:
    metrics:
      export:
        enabled: false

graphql-props:
  port: 8080
  url: localhost

spring:
  ai:
    vectorstore.type: none
    mcp:
      server:
        stdio: true
        enabled: true
  docker:
    compose:
      enabled: false