server.port: 8081
logging.config: classpath:logback-mcp-tool-gateway.xml
gateway:
  artifact-cache: file:.cache


otel:
  instrumentation:
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    jdbc:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
management:
  otlp:
    metrics:
      export:
        enabled: false

graphql-props:
  port: 8080
  url: localhost

spring:
  main:
    banner-mode: off
  ai:
    vectorstore.type: none
    mcp:
      server:
        stdio: true
        enabled: true
        type: sync
        name: "mcp-tool-gateway"
        version: 1.0.0

  docker:
    compose:
      enabled: false


