gateway:
  deployable-mcp-servers:
    commit-diff-context-mcp:
      name: commit-diff-context-mcp
      command: ./gradlew :commit-diff-context-mcp bootjar
      directory: /Users/hayde/IdeaProjects/commit-diff-context-parent
      copy-from-artifact-path: commit-diff-context-mcp/build/libs/commit-diff-context-mcp.jar
      copy-to-artifact-path: /Users/hayde/IdeaProjects/commit-diff-context-parent/mcp-tool-gateway/ctx_bin
  fail-on-mcp-client-init: false
  mcp-servers-json-location: classpath:mcp-servers/servers-prod.json

server.port: 8081

otel:
  instrumentation:
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    jdbc:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
management:
  otlp:
    metrics:
      export:
        enabled: false

graphql-props:
  port: 8080
  url: localhost

spring:
  ai:
    vectorstore.type: none
    mcp:
      server:
        stdio: true
        enabled: true
  docker:
    compose:
      enabled: false