server.port: 8081
logging.config: classpath:logback-mcp-tool-gateway.xml
gateway:
  artifact-cache: file:.cache
  kill-script: file:{{BUILD_DIR}}/resources/main/kill-cdc.sh

otel:
  instrumentation:
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    jdbc:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
management:
  otlp:
    metrics:
      export:
        enabled: false


graphql-props:
  port: 8084
  url: http://localhost:8084/graphql

spring:
  main:
    banner-mode: off
  ai:
    vectorstore.type: none
    mcp:
      server:
        stdio: true
        enabled: true
        type: sync
        name: "mcp-tool-gateway"
        version: 1.0.0
      client:
        name: replace-name

  docker:
    compose:
      file: file:/Users/hayde/IdeaProjects/commit-diff-context-parent/mcp-tool-gateway/src/main/resources/docker/docker-compose.yml
      enabled: false
      skip:
        in-tests: true
      lifecycle-management: start_and_stop
      start:
        skip: if_running
      readiness:
        wait: only_if_started


keystore:
  key-path: {{PROJ_DIR}}/keys
  key-name: cdc-key
