authorization-server:
  base-uri: http://cdc-commit-diff-context-authorization:8080

logging.config: classpath:logback.xml

keystore:
  key-path: ${KEY_PATH:{{PROJ_DIR}}/keys}
  key-name: cdc-key

gateway:
  deployable-mcp-servers:
    commit-diff-context-mcp:
      name: commit-diff-context-mcp
      command: bash
      arguments: gradlew commit-diff-context-mcp:bootJar
      directory: {{PARENT_DIR}}
      copy-to-artifact-path: /ctx_bin
      copy-from-artifact-path: commit-diff-context-mcp.jar
      mcp-deploy-log: {{PROJ_DIR}}/commit-diff-context-mcp.log
  kill-script: classpath:/kill-cdc.sh
  fail-on-mcp-client-init: false
  mcp-stdio-servers-json-location: classpath:/stdio-mcp-servers/servers-empty.json
  mcp-http-servers-json-location: classpath:/stdio-mcp-servers/servers-empty.json
  enable-redeployable: false

server.port: 8081


otel:
  instrumentation:
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    jdbc:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
management:
  otlp:
    metrics:
      export:
        enabled: false

graphql-props:
  port: 8084
  url: http://localhost:8084/graphql

spring:
  ai:
    vectorstore.type: none
    mcp:
      server:
        stdio: false
        enabled: true
  docker:
    compose:
      file: file:/Users/hayde/IdeaProjects/commit-diff-context-parent/mcp-tool-gateway/src/main/resources/docker/docker-compose.yml
      enabled: false